SOURCE.C   = Depot_i.C \
             DepotDat.C \
             Srv_Main.C

APPL = CentralServer
INCLUDE = -I. -I../IDL -I../POS -I../store -I../util -I$(PBHOME)/include
LIBRARY =  -L../IDL -L$(PBHOME)/lib -lstubs -lunixsvc -lcorba -lpbroker
CFLAGS = -g -c $(INCLUDE)
OTHEROBJS = ../util/FindPNS.o

include $(PBHOME)/make/make.cfg

all $(APPL): $(OBJECTS)
	$(CC) -g -o $(APPL) $(OBJECTS) $(OTHEROBJS) $(LIBRARY) -lnsl -lsocket

clean:
	rm -f *.o core $(APPL) .nse_depinfo .make.state
