#if !defined(AFX__ACTIVELISTBOX_H__DBCC2E7A_8A42_11D3_9E84_00E029175834__INCLUDED_)
#define AFX__ACTIVELISTBOX_H__DBCC2E7A_8A42_11D3_9E84_00E029175834__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// C_ActiveListBox wrapper class

class C_ActiveListBox : public CWnd
{
protected:
	DECLARE_DYNCREATE(C_ActiveListBox)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0x898619bb, 0x8a49, 0x11d3, { 0x9e, 0x84, 0x0, 0xe0, 0x29, 0x17, 0x58, 0x34 } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:

// Operations
public:
	void AddItem(BSTR* line);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX__ACTIVELISTBOX_H__DBCC2E7A_8A42_11D3_9E84_00E029175834__INCLUDED_)
