// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "_activelistbox.h"

/////////////////////////////////////////////////////////////////////////////
// C_ActiveListBox

IMPLEMENT_DYNCREATE(C_ActiveListBox, CWnd)

/////////////////////////////////////////////////////////////////////////////
// C_ActiveListBox properties

/////////////////////////////////////////////////////////////////////////////
// C_ActiveListBox operations

void C_ActiveListBox::AddItem(BSTR* line)
{
	static BYTE parms[] =
		VTS_PBSTR;
	InvokeHelper(0x60030002, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 line);
}
