/********************************************************
 FILE: neo/compat.hh

 DISCLAIMER: This code associated with this publication is intended to
 server solely as a programming example.  While this code is believed
 to be accurate, none of the Copyright holders makes any warranty of
 any kind for this code including but not limited to the implied
 warranties of merchantability and fitness for a particular purpose.
 None of the Copyright holders shall be liable for errors contained
 herein, or for incidental or consequential damages in connection with
 the furnishing, performance or use of this material at any time.

 Copyright 1995 by
  Object Management Group
  IONA Technologies, Ltd.
  Expersoft Inc.
  SunSoft, Inc.
  IBM Inc.
  Hewlett-Packard Company, Inc.
  International Computers Ltd.
  Digital Equipment Corporation
 All rights are reserved under the applicable copyright laws.

********************************************************/
#ifndef __COMPAT_HH__
#define __COMPAT_HH__


#define ORB_var 		ORBRef
#define Object_var 		ObjectRef
#define PseudoNameService_var 	PseudoNameServiceRef
#define OutputMedia_var 	OutputMediaRef 	
#define InputMedia_var 		InputMediaRef
#define POSList_var 		POSList*
#define ItemInfo_var 		ItemInfo*
#define POSTerminal_var 	POSTerminalRef
#define Tax_var			TaxRef
#define Store_var		StoreRef
#define StoreAccess_var		StoreAccessRef
#define Depot_var 		DepotRef


#define ORB_ptr 		ORBRef
#define Object_ptr 		ObjectRef
#define PseudoNameService_ptr 	PseudoNameServiceRef
#define OutputMedia_ptr 	OutputMediaRef 	
#define InputMedia_ptr 		InputMediaRef
#define POSList_ptr 		POSList*
#define ItemInfo_ptr 		ItemInfo*
#define POSTerminal_ptr 	POSTerminalRef
#define Tax_ptr			TaxRef
#define Store_ptr		StoreRef
#define StoreAccess_ptr		StoreAccessRef
#define Depot_ptr 		DepotRef

#endif //!__COMPAT_HH__
