//(c) Copyright 1996 HEWLETT-PACKARD COMPANY
//          
//   To anyone who acknowledges that this file is provided "AS IS" 
//   WITH NO EXPRESS OR IMPLIED WARRANTY:
//   permission to use, copy, modify, and distribute this file for any 
//   purpose is hereby granted without fee, provided that the above 
//   copyright notice and this notice appear in all copies, and that 
//   the name of Hewlett-Packard Company not be used in advertising or 
//   publicity pertaining to distribution of the software without 
//   specific, written prior permission.  Hewlett-Packard Company 
//   makes no representations about the suitability of this software 
//   for any purpose.


#ifndef POS_IDL
#define POS_IDL

// File pos.idl
//
// Purpose:
// IDL definition of interfaces for objects in the Point Of Sale
// terminal in a food store
//

module POS {

   typedef long   POSId;
   typedef string Barcode;

   interface InputMedia {

      typedef string OperatorCmd;

      void         BarcodeInput(in Barcode Item);
      void         KeypadInput(in OperatorCmd Cmd);

   };

   interface OutputMedia {

      boolean      OutputText(in string StringToPrint );

   };

   interface POSTerminal {


      void  Login();
      void  PrintPOSSalesSummary();
      void  PrintStoreSalesSummary();
      void  SendBarcode(in Barcode Item);
      void  ItemQuantity (in long Quantity);
      void  EndOfSale();

   };

};

#endif
