#ifndef lint
static char *sccsid = "%W%";
#endif

/*
 *   (C) COPYRIGHT International Business Machines Corp. 1995, 1996
 *   All Rights Reserved
 *   Licensed Materials - Property of IBM
 *   US Government Users Restricted Rights - Use, duplication or
 *   disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
 *
 *   DISCLAIMER OF WARRANTIES.
 *   The following [enclosed] code is sample code created by IBM
 *   Corporation. This sample code is not part of any standard or IBM
 *   product and is provided to you solely for the purpose of assisting
 *   you in the development of your applications.  The code is provided
 *   "AS IS". IBM MAKES NO WARRANTIES, EXPRESS OR IMPLIED, INCLUDING BUT
 *   NOT LIMITED TO THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 *   FOR A PARTICULAR PURPOSE, REGARDING THE FUNCTION OR PERFORMANCE OF
 *   THIS CODE.  IBM shall not be liable for any damages arising out of
 *   your use of the sample code, even if they have been advised of the
 *   possibility of such damages.
 *
 *   DISTRIBUTION.
 *   This sample code can be freely distributed, copied, altered, and
 *   incorporated into other software, provided that it bears the above
 *   Copyright notice and DISCLAIMER intact.
 */

/*
 *  This file was generated by the SOM Compiler.
 *  Generated using:
 *     SOM incremental update: 2.41
 */


#define SOM_Module_central_Source
#include <corba12.h>
#include <pos.h>
#include <store.h>
#include <central.ih>
#include <somdserv.h>
#include <somd.h>
#include <pnamesvc.h>
#include <db.h>

#define MAX_STR_LENGTH    64
            
#define DEPOT_FILE       "depot.dat"  /* The depot product data file  */

#undef FN
#define FN "CentralOffice_Depot_FindItemInfo()"

/*
 *-----------------------------------------------------------------------------
 * Structure definition for object state
 *-----------------------------------------------------------------------------
 */
typedef struct tagDepotState
{
  DbDb  db;

} DepotState;


/*
 *-----------------------------------------------------------------------------
 *  type definition of the structure that is saved in the  
 *  the database for each barcode                          
 *-----------------------------------------------------------------------------
 */

typedef  struct _item {
    CORBA_char barcode[MAX_STR_LENGTH];
    ItemTypes  itemType;
    CORBA_float cost;
    CORBA_char description[MAX_STR_LENGTH];
    CORBA_long quantity;
} item_s, *item_p;


BarcodeNotFound  BarcodeError;
SOM_Scope void  SOMLINK CentralOffice_DepotFindItemInfo(CentralOffice_Depot somSelf, 
                                                         Environment *ev, 
                                                        AStore_AStoreId StoreId, 
                                                        POS_Barcode Item, 
                                                        long Quantity, 
                                                        AStore_ItemInfo* IInfo)
{
   
    item_p           theItem;
    ItemInfo 	     theItemInfo; 
    DepotState       *ostate;
    
    
    CentralOffice_DepotData *somThis = CentralOffice_DepotGetData(somSelf);
    CentralOffice_DepotMethodDebug("CentralOffice_Depot","CentralOffice_DepotFindItemInfo");

    
    /*
     *  try to locate the item in the database   
     *  if it exists, set item_info              
     *  if it does not exist, throw an exception 
     */
    
    ostate = (DepotState *) somThis->ostate;
    
    if (theItem = db_lookup ((char *)Item, ostate->db)) {

	IInfo->Item        = theItem->barcode;
	IInfo->Itemtype    = theItem->itemType;
	IInfo->Itemcost    = theItem->cost;
	IInfo->Name        = theItem->description;
	IInfo->Quantity    = theItem->quantity;

	printf(FN " has returned the following ItemInfo record:\n");
	printf("barcode     = %s\n",IInfo->Item);
	printf("cost        = %.2f\n",IInfo->Itemcost);
	printf("description = %s\n",IInfo->Name);
	printf("quantity    = %d\n",IInfo->Quantity);
        printf("type        = %d\n",IInfo->Itemtype);

        theItem->quantity -= Quantity;

	return;
    }
    else {

	/**  barcode was not found, raise exception  **/

        BarcodeError.item = Item;
	CORBA_BOA_set_exception(SOMD_SOMOAObject, ev, CORBA_USER_EXCEPTION, 
				ex_AStore_BarcodeNotFound,
                                (void*) &BarcodeError);
			
        printf( FN " : Barcode %s not found\n",Item);

	return;
    }
}


SOM_Scope void SOMLINK CentralOffice_DepotsomDefaultInit(CentralOffice_Depot somSelf, 
                                                         somInitCtrl* ctrl)
{
    FILE                 *fp;
    CORBA_char           code[MAX_STR_LENGTH],
                         desc[MAX_STR_LENGTH],
                         itemType[MAX_STR_LENGTH];
    CORBA_long           quantity;
    CORBA_float          cost;
    item_p               anItem;
    CORBA_Environment    ev;
    DepotState           *ostate;

    CentralOffice_DepotData *somThis; /* set in BeginInitializer */
    somInitCtrl globalCtrl;
    somBooleanVector myMask;
    CentralOffice_DepotMethodDebug("CentralOffice_Depot","somDefaultInit");
    CentralOffice_Depot_BeginInitializer_somDefaultInit;

    CentralOffice_Depot_Init_SOMDServer_somDefaultInit(somSelf, ctrl);
    
    /* initialize the CORBA_Environment structure */

    SOM_InitEnvironment(&ev);

    /*  Create and initialize the database   */

     ostate      = SOMMalloc (sizeof(DepotState));
     somThis->ostate     = ostate;
     ostate->db  = db_init();

     /*
      *  Now open and read the depot data file. 
      *  Each "record" is saved in the database. The primary (only) 
      *  key is the barcode for the database operations.   
      */

     fp = fopen (DEPOT_FILE, "r");
    
     if(!fp)
     {
	 printf("%s could not be opened\n", DEPOT_FILE);
	 exit (1);
     }

     while (fscanf (fp, "%s%s%f%s%d", 
		        code, itemType, &cost, desc, &quantity) == 5) {
	 
	 anItem = SOMMalloc (sizeof(item_s));
	 if (anItem) {
	     strcpy (anItem->barcode, code);
	     strcpy (anItem->description, desc);
	     anItem->cost = cost;
	     anItem->quantity = quantity;
             if (!strcmp(itemType, "food"))
		 anItem->itemType = AStore_food;	
	     else if (!strcmp(itemType, "clothes"))
		 anItem->itemType = AStore_clothes;
	     else if (!strcmp(itemType, "other"))
		 anItem->itemType = AStore_other;
             db_insert (anItem->barcode, anItem, NULL, ostate->db);
	 }
     }
     
    fclose (fp);


    /* register with the PseudoNameService */
    
    register_server(&ev,somSelf);

    /*  clean up */
    SOM_UninitEnvironment(&ev);

    printf("Depot server initialized and ready\n");
    fflush (stdout);
}

SOM_Scope void SOMLINK CentralOffice_DepotsomDestruct(CentralOffice_Depot somSelf, 
                                                      octet doFree, 
                                                      somDestructCtrl* ctrl)
{
    CentralOffice_DepotData *somThis; /* set in BeginDestructor */
    somDestructCtrl globalCtrl;
    somBooleanVector myMask;
    CentralOffice_DepotMethodDebug("CentralOffice_Depot","CentralOffice_DepotsomDestruct");
    CentralOffice_Depot_BeginDestructor;
    CentralOffice_Depot_EndDestructor;
}




