/*
 *   (C) COPYRIGHT International Business Machines Corp. 1995, 1996
 *   All Rights Reserved
 *   Licensed Materials - Property of IBM
 *   US Government Users Restricted Rights - Use, duplication or
 *   disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
 *
 *   DISCLAIMER OF WARRANTIES.
 *   The following [enclosed] code is sample code created by IBM
 *   Corporation. This sample code is not part of any standard or IBM
 *   product and is provided to you solely for the purpose of assisting
 *   you in the development of your applications.  The code is provided
 *   "AS IS". IBM MAKES NO WARRANTIES, EXPRESS OR IMPLIED, INCLUDING BUT
 *   NOT LIMITED TO THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 *   FOR A PARTICULAR PURPOSE, REGARDING THE FUNCTION OR PERFORMANCE OF
 *   THIS CODE.  IBM shall not be liable for any damages arising out of
 *   your use of the sample code, even if they have been advised of the
 *   possibility of such damages.
 *
 *   DISTRIBUTION.
 *   This sample code can be freely distributed, copied, altered, and
 *   incorporated into other software, provided that it bears the above
 *   Copyright notice and DISCLAIMER intact.
 */

/*
 *  This file was generated by the SOM Compiler.
 *  Generated using:
 *     SOM incremental update: 2.41
 */

#define SOM_Module_pos_Source
#include <corba12.h>
#include <pos.ih>
#include <store.h>
#include <central.h>
#include <stdio.h>
#include <orb.h>
#include <pnamesvc.h>
#include <common.h>

#include <ctype.h>
#include <stdlib.h>

typedef struct tagImState
{
  POS_POSTerminal  _posreference;
  POS_POSId        _id;
  CORBA_char       *pos_name;

} ImState;

typedef struct tagOmState
{
  char *name;
  CORBA_long id;

} OmState;

typedef struct tagPOSTermState
{
  CORBA_float         _saleSubtotal;
  CORBA_long          _quantity;
  POS_POSId           _posid;
  AStore_AStoreId     _storeid;
  CORBA_float         _saleTaxableSubtotal;
  AStore_StoreAccess  _accessreference;
  AStore_Store        _storereference;
  POS_OutputMedia     _outputreference;
  AStore_Tax          _taxreference;
  CORBA_char          *store_name;
  CORBA_char          *om_name;
  CORBA_char          *tax_name;
  CORBA_char          *pos_name;

} POSTermState;

char *posid, *storeid;

SOM_Scope void  SOMLINK POS_InputMediaBarcodeInput(POS_InputMedia somSelf, 
                                                    Environment *ev, 
                                                   POS_Barcode Item)
{
    ImState  *ostate;
    POS_InputMediaData *somThis = POS_InputMediaGetData(somSelf);
    POS_InputMediaMethodDebug("POS_InputMedia","POS_InputMediaBarcodeInput");

    ostate = (ImState *) somThis->ostate;
    POS_POSTerminal_SendBarcode(ostate->_posreference, ev, Item);
    if(ev->_major != CORBA_NO_EXCEPTION) handle_error(ev);
} /* end of POS_InputMedia_InputMediaBarcodeInput() */

SOM_Scope void  SOMLINK POS_InputMediaKeypadInput(POS_InputMedia somSelf, 
                                               Environment *ev, 
                                               POS_InputMedia_OperatorCmd Cmd)
{
    ImState  *ostate;
    POS_InputMediaData *somThis = POS_InputMediaGetData(somSelf);
    POS_InputMediaMethodDebug("POS_InputMedia","POS_InputMediaKeypadInput");

    ostate = (ImState *) somThis->ostate;
    switch (toupper(Cmd[0]))
    {
    case 'L':
	POS_POSTerminal_Login(ostate->_posreference,ev);
	if(ev->_major != CORBA_NO_EXCEPTION) handle_error(ev);
	break;
    case 'P':
	POS_POSTerminal_PrintPOSSalesSummary(ostate->_posreference, ev);
	if(ev->_major != CORBA_NO_EXCEPTION) handle_error(ev);
	break;
    case 'S':
	POS_POSTerminal_PrintStoreSalesSummary(ostate->_posreference, ev);
	if(ev->_major != CORBA_NO_EXCEPTION) handle_error(ev);
	break;
    case 'T':
	POS_POSTerminal_EndOfSale(ostate->_posreference, ev);
	if(ev->_major != CORBA_NO_EXCEPTION) handle_error(ev);
	break;
    case 'Q':
	POS_POSTerminal_ItemQuantity(ostate->_posreference, ev, atol(++Cmd));
	if(ev->_major != CORBA_NO_EXCEPTION) handle_error(ev);
	break;
    default: printf("input ignored\n"); /* ignore */
    }
    return;
}/* end of POS_InputMedia_KeypadInput() */

SOM_Scope void SOMLINK POS_InputMediasomDefaultInit(POS_InputMedia somSelf, 
                                                    somInitCtrl* ctrl)
{
    ImState *ostate;
    POS_InputMediaData *somThis; /* set in BeginInitializer */
    somInitCtrl globalCtrl;
    somBooleanVector myMask;
    POS_InputMediaMethodDebug("POS_InputMedia","somDefaultInit");
    POS_InputMedia_BeginInitializer_somDefaultInit;
    POS_InputMedia_Init_SOMObject_somDefaultInit(somSelf, ctrl);
    
    /*
     *  create the POSTerminal object and store it in the ostate
     *  structure  instance variable  
     */
    
    ostate = SOMCalloc (1, sizeof(ImState));
    ostate->_posreference = POS_POSTerminalNew();
    somThis->ostate = ostate;
    return;
}

SOM_Scope void SOMLINK POS_InputMediasomDestruct(POS_InputMedia somSelf, 
                                                 octet doFree, 
                                                 somDestructCtrl* ctrl)
{
    POS_InputMediaData *somThis; /* set in BeginDestructor */
    somDestructCtrl globalCtrl;
    somBooleanVector myMask;
    POS_InputMediaMethodDebug("POS_InputMedia","POS_InputMediasomDestruct");
    POS_InputMedia_BeginDestructor;
    POS_InputMedia_EndDestructor;
    
    SOMFree (somThis->ostate);
    return;
}

SOM_Scope boolean  SOMLINK POS_OutputMediaOutputText(POS_OutputMedia somSelf, 
                                                      Environment *ev, 
                                                     string StringToPrint)
{
    /* POS_OutputMediaData *somThis = POS_OutputMediaGetData(somSelf); */
    POS_OutputMediaMethodDebug("POS_OutputMedia","POS_OutputMediaOutputText");

    return(printf("%s", StringToPrint));
} /* end of POS_OutputMedia_OutputText() */

SOM_Scope void SOMLINK POS_OutputMediasomDefaultInit(POS_OutputMedia somSelf, 
                                                     somInitCtrl* ctrl)
{
    PseudoNameService pnsRef;
    SOMDObject        sdo;

    POS_OutputMediaData *somThis; /* set in BeginInitializer */
    somInitCtrl globalCtrl;
    somBooleanVector myMask;

    CORBA_Environment ev;

    POS_OutputMediaMethodDebug("POS_OutputMedia","somDefaultInit");
    POS_OutputMedia_BeginInitializer_somDefaultInit;

    POS_OutputMedia_Init_SOMDServer_somDefaultInit(somSelf, ctrl);

    SOM_InitEnvironment(&ev);
 
    register_server(&ev,somSelf);

    /** clean up **/

    SOM_UninitEnvironment(&ev);

    printf("OutputMedia server initialized and ready\n");

    return;

}

SOM_Scope void SOMLINK POS_OutputMediasomDestruct(POS_OutputMedia somSelf, 
                                                  octet doFree, 
                                                  somDestructCtrl* ctrl)
{
    POS_OutputMediaData *somThis; /* set in BeginDestructor */
    somDestructCtrl globalCtrl;
    somBooleanVector myMask;
    POS_OutputMediaMethodDebug("POS_OutputMedia",
			       "POS_OutputMediasomDestruct");
    POS_OutputMedia_BeginDestructor;
    POS_OutputMedia_EndDestructor;
}

SOM_Scope void  SOMLINK POS_POSTerminalLogin(POS_POSTerminal somSelf, 
                                              Environment *ev)
{
    POSTermState   *ostate;
    POS_POSTerminalData *somThis = POS_POSTerminalGetData(somSelf);
    POS_POSTerminalMethodDebug("POS_POSTerminal","POS_POSTerminalLogin");

    ostate = (POSTermState *)somThis->ostate;

    /* check to see if we are in the middle of a sale */

    if (ostate->_saleSubtotal != 0 || ostate->_quantity != 1) 
    {
	printf("POSTerminal_login - login ignored, sale in progress\n");
	return;
    }
    else
    {
	/** log in to the Store and get StoreAccess object **/

	ostate->_accessreference 
                    = AStore_Store_Login(ostate->_storereference,
					 ev,
					 ostate->_posid);
	EX_TERM("cant access store\n", ev);
	printf("POS::login - logged into Store\n");
	
    }
}/* end of POS_POSTerminal_Login() */

SOM_Scope void  SOMLINK POS_POSTerminalPrintPOSSalesSummary(POS_POSTerminal somSelf, 
                                                             Environment *ev)
{
    CORBA_char      outstring[STR_MAX];
    AStore_POSList  poslist;
    CORBA_long      count = 0;
    CORBA_short     found = 0;
    POSTermState     *ostate;

    POS_POSTerminalData *somThis = POS_POSTerminalGetData(somSelf);
    POS_POSTerminalMethodDebug("POS_POSTerminal",
			       "POS_POSTerminalPrintPOSSalesSummary");

    ostate = (POSTermState *) somThis->ostate;

    printf("POS::print_POS_sales_summary - \n");

    /*  check to see if we are in the middle of a sale */

    if (ostate->_saleSubtotal != 0 || ostate->_quantity != 1)
    { 
	printf("POS_POSTerminal_PrintPOSSalesSummary - ignored, sale in progress\n");
	return;
    }
    
    /**  get poslist from store **/

    AStore_Store_GetPOSTotals(ostate->_storereference, ev,&poslist);
    if(ev->_major != CORBA_NO_EXCEPTION) handle_error(ev);
    /*  look for POSId in poslist */

    while ((count < poslist._length) && (!found))
      {
	   if (poslist._buffer[count].Id == ostate->_posid) found = 1;
	   count++;
       }

    if (!found)
    {
	printf("POS_POSTerminal_PrintPOSSalesSummary: POS %d not found\n", 
				ostate->_posid);
	CORBA_free(&poslist);
	return;
    }
    else
    {
	sprintf(outstring,"Total POS sales = %.2f   Total POS taxes = %.2f\n", 
		poslist._buffer[count-1].TotalSales, 
                poslist._buffer[count-1].TotalTaxes);
        POS_OutputMedia_OutputText(ostate->_outputreference,ev,outstring);
	if(ev->_major != CORBA_NO_EXCEPTION) handle_error(ev);
	CORBA_free(&poslist);
	return;
    }
} /* end of POS_POSTerminal_PrintPOSSalesSummary() */

SOM_Scope void  SOMLINK POS_POSTerminalPrintStoreSalesSummary(POS_POSTerminal somSelf, 
                                                               Environment *ev)
{
    CORBA_char               outstring[STR_MAX];
    AStore_POSList           poslist;
    AStore_Store_StoreTotals storetotals;
    CORBA_long               count;
    POSTermState             *ostate;

    POS_POSTerminalData *somThis = POS_POSTerminalGetData(somSelf);
    POS_POSTerminalMethodDebug("POS_POSTerminal",
			       "POS_POSTerminalPrintStoreSalesSummary");

    ostate = (POSTermState *)somThis->ostate;

    /*  check to see if we are in the middle of a sale */

    if (ostate->_saleSubtotal != 0 || ostate->_quantity != 1)
    { 
	printf("POS_POSTerminal_PrintStoreSalesSummary - ignored, sale in progress\n");
	return;
    }

    printf("POS::print_POS_sales_summary -\n");
 
    /*  get and print the totals for the Store */

    storetotals = AStore_Store__get_Totals(ostate->_storereference, ev);
    sprintf(outstring, "Store total = %.2f   Store tax = %.2f\n",
	    storetotals.StoreTotal, 
	    storetotals.StoreTaxTotal);

    POS_OutputMedia_OutputText(ostate->_outputreference,ev,outstring);
    if(ev->_major != CORBA_NO_EXCEPTION) handle_error(ev);
    /**  get the poslist from the Store object  **/

    AStore_Store_GetPOSTotals(ostate->_storereference,ev,&poslist);
    if(ev->_major != CORBA_NO_EXCEPTION) handle_error(ev);

    /*  run through the list, printing out the totals  */

    for (count = 0; count < poslist._length; count++)
    {
      sprintf(outstring," POSID = %d   POSTotal =  %.2f  POSTaxTotal = %.2f\n",
		poslist._buffer[count].Id, poslist._buffer[count].TotalSales,
		poslist._buffer[count].TotalTaxes);
	
	POS_OutputMedia_OutputText(ostate->_outputreference,ev,outstring);
	if(ev->_major != CORBA_NO_EXCEPTION) handle_error(ev);
    }

    /*  free returned memory  */

    CORBA_free(&poslist);
    return;
} /* end of POS_POSTerminal_PrintStoreSalesSummary() */


SOM_Scope void  SOMLINK POS_POSTerminalSendBarcode(POS_POSTerminal somSelf, 
                                                    Environment *ev, 
                                                   POS_Barcode Item)
{
    CORBA_char outstring[STR_MAX];
    CORBA_float     itemprice,
                    itemtaxprice;
    AStore_ItemInfo iteminfo;
    POSTermState    *ostate;

    POS_POSTerminalData *somThis = POS_POSTerminalGetData(somSelf);
    POS_POSTerminalMethodDebug("POS_POSTerminal",
			       "POS_POSTerminalSendBarcode");

    ostate = (POSTermState *) somThis->ostate;
    printf("POS::send_barcode - \n");

    /*  call FindPrice on the StoreAccess object  */

    AStore_StoreAccess_FindPrice(ostate->_accessreference,
				 ev, Item,
				 ostate->_quantity,
				 &itemprice, &itemtaxprice, &iteminfo);
    
    /*  check for and handle exception  */

    if (ev->_major == CORBA_SYSTEM_EXCEPTION)
    {
       /* just refer error to client */
      return;
    }
    else if (ev->_major == CORBA_USER_EXCEPTION)
    {
	CORBA_exception_free (ev);
        ostate->_quantity = 1;
	return;
    }

    /*  accumulate totals for the current sale  */

    ostate-> _saleSubtotal       += itemprice * ostate->_quantity;
    ostate->_saleTaxableSubtotal += itemtaxprice * ostate->_quantity;

    /*  print out information with format depending upon whether item is */
    /*  taxable or not                                                   */

    if (itemtaxprice)
	sprintf(outstring,"%s*  %s  %d   %.2f  %.2f\n", iteminfo.Item,
		iteminfo.Name,
		ostate->_quantity,
		itemprice, 
		itemprice * ostate->_quantity);
    else
	sprintf(outstring,"%s  %s  %d   %.2f  %.2f\n", iteminfo.Item,
		iteminfo.Name,
		ostate->_quantity,
		itemprice, 
		itemprice * ostate->_quantity);

    POS_OutputMedia_OutputText(ostate->_outputreference, ev, outstring);
    if(ev->_major != CORBA_NO_EXCEPTION) handle_error(ev);

    /*  free memory and reset quantity instance variable  */

    CORBA_free(&iteminfo);
    ostate->_quantity = 1;

    return;
} /* end of POS_POSTerminal_SendBarcode() */

SOM_Scope void  SOMLINK POS_POSTerminalItemQuantity(POS_POSTerminal somSelf, 
                                                     Environment *ev, 
                                                    long Qty)
{
    POSTermState   *ostate;
    POS_POSTerminalData *somThis = POS_POSTerminalGetData(somSelf);
    POS_POSTerminalMethodDebug("POS_POSTerminal",
			       "POS_POSTerminalItemQuantity");

    ostate = (POSTermState *) somThis->ostate;

    printf("POS_POSTerminal_ItemQuantity = %d\n",Qty);
    ostate->_quantity = Qty;
}  /* end of POS_POSTerminal_ItemQuantity() */

SOM_Scope void  SOMLINK POS_POSTerminalEndOfSale(POS_POSTerminal somSelf, 
                                                  Environment *ev)
{
    CORBA_float      tax;
    CORBA_char       outstring[STR_MAX];
    POSTermState     *ostate;

    POS_POSTerminalData *somThis = POS_POSTerminalGetData(somSelf);
    POS_POSTerminalMethodDebug("POS_POSTerminal","POS_POSTerminalEndOfSale");

    ostate = (POSTermState *) somThis->ostate;
    printf("POS::EndOfSale -\n");

    /*
     * make sure we are in a sale
     * total should not be zero
     */

    if (ostate->_saleSubtotal == 0)
    {
	printf("EndOfSale ignored, there is no sale in progress\n"); 
        return;
    }

    /* quantity should be 1 */
    if (ostate->_quantity != 1)
    {
	printf("EndOfSale ignored, transaction in progress\n");
	return;
    }

    /** get tax **/

    tax = AStore_Tax_CalculateTax(ostate->_taxreference, ev,
				  ostate->_saleTaxableSubtotal);

    /* update store total */

    AStore_Store_UpdateStoreTotals(ostate->_storereference, ev, 
				   ostate->_posid,
				   ostate->_saleSubtotal, tax);

    /* format string and send text to OutputMedia */

   sprintf(outstring," Subtotal  %7.2f\n Tax       %7.2f\n Total     %7.2f\n",
	    ostate->_saleSubtotal, tax, ostate->_saleSubtotal + tax);
    
    POS_OutputMedia_OutputText(ostate->_outputreference, ev, outstring);

    /* zero out subtotal accumulators and reset quantity */

    ostate->_saleSubtotal = 0.0;
    ostate->_saleTaxableSubtotal = 0.0;
    ostate->_quantity = 1;
} /* end of POS_POSTerminal_EndOfSale() */

SOM_Scope void SOMLINK POS_POSTerminalsomDefaultInit(POS_POSTerminal somSelf, 
                                                     somInitCtrl* ctrl)
{
    POS_POSTerminalData *somThis; /* set in BeginInitializer */
    somInitCtrl globalCtrl;
    somBooleanVector myMask;
    POSTermState       *ostate;
    PseudoNameService pnsRef;
    CORBA_Environment ev;
    CORBA_char        namestr[STR_MAX];

    POS_POSTerminalMethodDebug("POS_POSTerminal","somDefaultInit");
    POS_POSTerminal_BeginInitializer_somDefaultInit;

    POS_POSTerminal_Init_SOMObject_somDefaultInit(somSelf, ctrl);

    /** initialize the CORBA_Environment structure **/

    SOM_InitEnvironment(&ev);

    /** set the posid **/
    ostate =  SOMCalloc(1, sizeof(POSTermState));
    somThis->ostate = ostate;
    ostate->_posid = atol(posid);
    ostate->_storeid = atol(storeid);

    printf("POSID = %d\n",ostate->_posid);

    /** get an object reference to the PseudoNameService **/

    pnsRef = file_to_ref(&ev,PNAME_REF);
    if(ev._major != CORBA_NO_EXCEPTION) handle_error(&ev);

    /* get the Store object reference from the PNS */
    
    
    sprintf (namestr, "%s%s", "storesvr_" ,storeid);
    ostate->_storereference = PseudoNameService_ResolveName(pnsRef,
							    &ev, namestr);
    if(ev._major != CORBA_NO_EXCEPTION) handle_error(&ev);

    if(CORBA_Object_is_nil(ostate->_storereference,&ev))
    {
	printf("cannot find: %s\n", namestr);
	exit(1);
     }

    /* get the Tax object reference from the PNS */

    ostate->_taxreference = PseudoNameService_ResolveName(pnsRef, &ev, "tax");
    if(ev._major != CORBA_NO_EXCEPTION) handle_error(&ev);
 
    if(CORBA_Object_is_nil(ostate->_taxreference,&ev))
    {
	printf("cannot find tax Object: %s\n", namestr);
	exit(1);
     }

    /* get the OutputMedia object reference from the PNS */

    sprintf (namestr, "%s%s", "outputsvr_" ,posid);
    ostate->_outputreference = PseudoNameService_ResolveName(pnsRef, &ev,
							     namestr);
    if(ev._major != CORBA_NO_EXCEPTION) handle_error(&ev);

    if(CORBA_Object_is_nil(ostate->_outputreference,&ev))
    {
	printf("cannot find media object : %s\n", namestr);
	exit(1);
    }

    /** free the PNS object reference **/

    CORBA_Object_release(pnsRef, &ev);
    if(ev._major != CORBA_NO_EXCEPTION) handle_error(&ev);

    /** clean up **/

    SOM_UninitEnvironment(&ev);

    ostate->_quantity = 1;
    return;
}

SOM_Scope void SOMLINK POS_POSTerminalsomDestruct(POS_POSTerminal somSelf, 
                                                  octet doFree, 
                                                  somDestructCtrl* ctrl)
{
    POS_POSTerminalData *somThis; /* set in BeginDestructor */
    somDestructCtrl globalCtrl;
    somBooleanVector myMask;
    POS_POSTerminalMethodDebug("POS_POSTerminal",
			       "POS_POSTerminalsomDestruct");
    POS_POSTerminal_BeginDestructor;
    POS_POSTerminal_EndDestructor;
}
