/*

Copyright (C) 1996 by Iona Technologies. All rights reserved.

Permission to use, copy, modify, and distribute this software for any
teaching or instructional purpose and without fee is hereby granted,
provided that the above copyright notice appear in all copies and that both
that copyright notice and this permission notice appear in supporting
documentation, and that the name of Iona Technologies Ltd. not be used in
advertising or publicity pertaining to distribution of the software without
specific, written prior permission.

THIS SOFTWARE IS SOLD AS IS WITHOUT WARRANTY OF ANY KIND, EITHER EXPRESSED
OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTY OF
MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.  Iona Technologies
Ltd. assume no liability of any alleged or actual damages arising from the
use of or the inability to use this software.

*/

#ifndef POS_IDL
#define POS_IDL

module POS {

   typedef long   POSId;
   typedef string Barcode;

   interface InputMedia {

      typedef string OperatorCmd;

      void         BarcodeInput(in string Item);
      void         KeypadInput(in string Cmd);

   };

   interface OutputMedia {

      boolean      OutputText(in string StringToPrint );

   };

   interface POSTerminal {


      void  Login();
      void  PrintPOSSalesSummary();
      void  PrintStoreSalesSummary();
      void  SendBarcode(in string Item);
      void  ItemQuantity (in long Quantity);
      void  EndOfSale();

   };

};

#endif
