//*****************************************************************************
//	VAO_ALL.CPP - Generated by the "MFC VAddon VSL Wizard."
//	Copyright (C) 1997 Visio Corporation. All rights reserved.

//	This file references the necessary vao_src\*.cpp files
//	which should be included in projects with VSL targets.

//*****************************************************************************
//	MANUAL STEPS NECESSARY TO BUILD THIS PROJECT:
//	(See copy of these comments in VAO_ALL.CPP)
//
//	<1>
//	Add the paths to "vao_inc" and "vao_src" to the project
//	include settings. The default location is in:
//	C:\Program Files\Visio\DVS\Libraries\C-CPP\vao_inc
//	C:\Program Files\Visio\DVS\Libraries\C-CPP\vao_src
//	Adjust accordingly for your own Visio\DVS installation.
//
//	<2>
//	Rename the output files *.VSL (rather than *.DLL)
//	Visio will not load plain *.DLL files to check for
//	an exported VisioLibMain. (See vaddon.cpp for the
//	implementation of VisioLibMain if you're curious!)


#include "stdafx.h"


#include "addsink.cpp"		//	For hooking up to Visio events
#include "helpers.cpp"		//	BSTR and VARIANT helper classes
#include "ivisreg.cpp"		//	Getting/creating an Automation instance of Visio
#include "vaddon.cpp"		//	The "easy-to-subclass" VAddon


extern "C" {

	#include "vao.c"		//	VSL utility functions

}

