//*****************************************************************************
//	VNETINFO.CPP - Generated by the "MFC VAddon VSL Wizard."
//	Copyright (C) 1997 Visio Corporation. All rights reserved.

#ifndef VNETINFO_H
#define VNETINFO_H

#include "vaddon.h"		//	parent class, VAddon
#include "visiwrap.h"	//	For driving Visio Automation via wrapper classes
								//	& the definition of CVisioApplication
// VSL properties.
#define ATTS (VAO_AOATTS_ISACTION | VAO_AOATTS_HASABOUT | VAO_AOATTS_WAITCRSR)

#define VNetInfo_PARENT VAddon

class VNetInfo : public VNetInfo_PARENT
{
public:		// c'tor/d'tor.
	VNetInfo(LPCTSTR pName);
	virtual ~VNetInfo();

public:		// Overrides
	virtual VAORC Run(LPVAOV2LSTRUCT pV2L);
	virtual VAORC IsEnabled(LPVAOV2LSTRUCT pV2L);
	virtual VAORC About(LPVAOV2LSTRUCT pV2L);
	virtual VAORC Load(WORD wVersion, LPVOID p);
	virtual VAORC Unload(WORD wParam, LPVOID p);
	virtual VAORC KillSession(LPVAOV2LSTRUCT pV2L);
	virtual HINSTANCE GetInstance(long nFlags= 0L);
	
	HRESULT GetApp(CVisioApplication &app);

private:		// Implementation
	CVisioApplication m_app;
};

extern VNetInfo g_vNetInfoAddon;

#endif // VNETINFO_H