/*
 * Depot Server Main
 * -----------------
 *
 * This module contains the main() for a server based on CENTRAL.idl
 * for Digital Equipment Corporation's (DEC) ObjectBroker C binding
 * and some convenience routines for use by the main. It was originally
 * generated by ObjectBroker's Quick Start utility and then modified to
 * be a little closer to the other vendors.
 *
 */

/* Include Files */
#include <orb.h>
#include <stdio.h>
#include <string.h>
#include "misc.h"
#include "central.imh"

/*
 *-----------------------------------------------------------------------------
 * global variables
 *-----------------------------------------------------------------------------
 */

CORBA_ImplementationDef   DepotImpl;   /*filled by RegisterDepotImpl routine, used by others*/
CORBA_ORB                 TheOrb;
CORBA_BOA                 TheBoa;

/*
 *-----------------------------------------------------------------------------
 * Forward Declarations
 *-----------------------------------------------------------------------------
 */

CORBA_boolean   RegisterDepotImpl (CORBA_Environment *ev);
void            depotmain_clean_up (CORBA_Environment *ev);

/*
 *-----------------------------------------------------------------------------
 * Special external declarations -- function prototypes
 *-----------------------------------------------------------------------------
 */

#define Create_CentralOffice_Depot_Object Create_CentralOffice_Depot_Obje
CORBA_Object Create_CentralOffice_Depot_Object(CORBA_long argc,
                                               CORBA_char **argv,
                                               CORBA_Environment *ev);

/*
 *
 *  ROUTINE NAME: Main
 *
 *  FUNCTIONAL DESCRIPTION:
 *
 *      This is a platform independent main for the Depot Server.
 */
CORBA_boolean main (int argc, char *argv[])
{
    /* local data declaration */
    CORBA_Environment   ev;

    printf("\n***** Depot Server Started Execution *****\n");

    /* convenience declarations, for similarity to other implementations */
    TheOrb = CORBA_DEC_ORB_OBJECT;
    TheBoa = CORBA_DEC_BOA_OBJECT;


    /* Register the implementation, declare it active */
    if (!RegisterDepotImpl (&ev))  /*side effect: sets global DepotImpl*/
        {
        OBB_ORB_rundown (TheOrb, &ev, (CORBA_Flags) 0);
        IsException (&ev,(CORBA_string) "OBB_ORB_rundown failed \n");
        return(0);
        }

    /*Create the object reference, register it with the name service*/
    (void)Create_CentralOffice_Depot_Object(argc, argv, &ev );

    /* Jump into the main loop. */
    OBB_BOA_main_loop (TheOrb, &ev, (CORBA_Flags)0 );

    /*Finished -- clean up so we don't leave any memory or registration information*/
    depotmain_clean_up(&ev);
    return(0);
}

/*
 *
 *  ROUTINE NAME: RegisterDepotImpl
 *
 *  FUNCTIONAL DESCRIPTION:
 *
 *      Routine to register and activate the Depot implementation
 *
 */
CORBA_boolean RegisterDepotImpl (CORBA_Environment *ev)
{
    /* Local Data Declaration */
    CORBA_Flags reg_flags=0;

    /* Register the DepotImpl. DepotImpl__register is created
       in the dispatch file by the "obbgen -d" command.*/
    DepotImpl = DepotImpl__register (
                        DepotImpl__OBJ,
                        ev,
                        (CORBA_NVList) NULL,   /*no additional attrs needed*/
                        (CORBA_NVList) NULL,   /*no server selection needed*/
                        reg_flags);
    if ((DepotImpl == NULL) || (IsException (ev,(CORBA_string)"")))
        {
        printf("DepotImpl__register failed \n");
        return(CORBA_FALSE);
        }

    /* Activate the implementation and check for success */
    if (!ActivateImpl(DepotImpl, ev))
        return (CORBA_FALSE);

    return(CORBA_TRUE);
 }

/*
 *****************************************************************************
 *
 * Function Name : depotmain_clean_up
 *
 * Role          : tidying up to be done.
 *
 *****************************************************************************
 */

void depotmain_clean_up(CORBA_Environment *ev)
{
    /*The first two routines routines are provided through QuickStart, so use
      them instead of worring about details*/
    DeactivateImpl(DepotImpl, ev);
    UnregisterImpl(DepotImpl, ev);
    CORBA_Object_release((CORBA_Object)DepotImpl, ev);
    OBB_ORB_rundown (TheOrb, ev, (CORBA_Flags) 0);
    printf("\n***Finished tidying up after depot service closed down***");
} /* end of depotmain_clean_up() */
