/*
 * OutputMedia Server Main
 * -----------------------
 *
 * This module contains the main() for an OutputMedia server based on POS.idl
 * for Digital Equipment Corporation's (DEC) ObjectBroker C binding
 * and some convenience routines for use by the main. It was originally
 * generated by ObjectBroker's Quick Start utility and then modified to
 * be a little closer to the other vendors.
 *
 */

/* Include Files */
#include <orb.h>
#include <stdio.h>
#include <string.h>
#include "misc.h"
#include "pos.imh"

/*
 *-----------------------------------------------------------------------------
 * global variables
 *-----------------------------------------------------------------------------
 */

CORBA_ImplementationDef   OutputMediaImpl;   /*filled by RegisterOutputMediaImpl routine, used by others*/
CORBA_ORB                 TheOrb;
CORBA_BOA                 TheBoa;

/*
 *-----------------------------------------------------------------------------
 * Forward Declarations
 *-----------------------------------------------------------------------------
 */

CORBA_boolean   RegisterOutputMediaImpl  (CORBA_Environment *ev);
void            OutputMediamain_clean_up (CORBA_Environment *ev);

/*
 *-----------------------------------------------------------------------------
 * Special external declarations -- function prototypes
 *-----------------------------------------------------------------------------
 */

CORBA_Object Create_POS_OutputMedia_Object(CORBA_long        argc,
                                           CORBA_char        **argv,
                                           CORBA_Environment *ev);


/*
 *
 *  ROUTINE NAME: Main
 *
 *  FUNCTIONAL DESCRIPTION:
 *
 *      This is a platform independent main for the OutputMedia Server.
 */
CORBA_boolean main (int argc, char *argv[])
{
    /* local data declaration */
    CORBA_Environment	ev;

    printf("\n***** OutputMedia Server Started Execution *****\n");

    /* convenience declarations, for similarity to other implementations */
    TheOrb = CORBA_DEC_ORB_OBJECT;
    TheBoa = CORBA_DEC_BOA_OBJECT;


    /* Register the implementation, declare it active */
    if (!RegisterOutputMediaImpl (&ev))  /*side effect: sets global OutputMediaImpl*/
        {
	OBB_ORB_rundown (TheOrb, &ev, (CORBA_Flags) 0);
	IsException (&ev,(CORBA_string) "OBB_ORB_rundown failed \n");
	return(0);
        }

    /*Create the object reference, register it with the name service*/
    (void)Create_POS_OutputMedia_Object(argc, argv, &ev );

    /* Jump into the main loop. */
    OBB_BOA_main_loop (TheOrb, &ev, (CORBA_Flags)0 );

    /*Finished -- clean up so we don't leave any memory or registration information*/
    OutputMediamain_clean_up(&ev);
    return(0);
}


/*
 *
 *  ROUTINE NAME: RegisterOutputMediaImpl
 *
 *  FUNCTIONAL DESCRIPTION:
 *
 *      Routine to register and activate the OutputMedia implementation
 *
 */
CORBA_boolean RegisterOutputMediaImpl (CORBA_Environment *ev)
{
    /* Local Data Declaration */
    CORBA_Flags reg_flags=0;

    /* Register the OutputMediaImpl. OutputMediaImpl__register is created
       in the dispatch file by the "obbgen -d" command.*/
    OutputMediaImpl = OutputMediaImpl__register (
                        OutputMediaImpl__OBJ,
                        ev,
                        (CORBA_NVList) NULL,   /*no additional attrs needed*/
                        (CORBA_NVList) NULL,   /*no server selection needed*/
                        reg_flags);
    if ((OutputMediaImpl == NULL) || (IsException (ev,(CORBA_string)"")))
        {
        printf("OutputMediaImpl__register failed \n");
        return(CORBA_FALSE);
        }

    /* Activate the implementation and check for success */
    if (!ActivateImpl(OutputMediaImpl, ev))
        {
        return (CORBA_FALSE);
        }

    return(CORBA_TRUE);
 }


/*
 *****************************************************************************
 *
 * Function Name : OutputMediamain_clean_up
 *
 * Role          : tidying up to be done.
 *
 *****************************************************************************
 */

void OutputMediamain_clean_up(CORBA_Environment *ev)
{
    /*The first two routines routines are provided through QuickStart, so use
      them instead of worring about details*/
    DeactivateImpl(OutputMediaImpl, ev);
    UnregisterImpl(OutputMediaImpl, ev);
    CORBA_Object_release((CORBA_Object)OutputMediaImpl, ev);
    OBB_ORB_rundown (TheOrb, ev, (CORBA_Flags) 0);

} /* end of OutputMediamain_clean_up() */
