/*
 *****************************************************************************
 *
 * File Name   : pname_m.c
 *
 * This module contains the main program for the pseudo name server for the
 * example. It contains convenience routines such as are generated for you
 * by the the ObjectBroker QuickStart utility. As such it may be structured
 * slightly differently than the C-binding examples of other vendors, although
 * we've tried to use some of the same structure. Typically, the QuickStart
 * utility would generate a skeleton main with calls to register implementations,
 * create objects, and clean up. QuickStart also uses a module of miscellaneous
 * routines that are always the same to make the job easier. This module follows
 * that structure.
 *
 * After QuickStart creates an initial main for you, you start filling in application
 * code and maintain the main yourself.
 *
 *****************************************************************************
 */

#include <orb.h>
#include "pnamesvc.imh"
#include "common.h"
#include "misc.h"

/*
 *-----------------------------------------------------------------------------
 * globals -- i.e. externals
 *-----------------------------------------------------------------------------
 */
CORBA_ImplementationDef PseudoNameServiceImpl;
PseudoNameService       pname_ref;

/*
 *-----------------------------------------------------------------------------
 * Special External Reference -- i.e., external function prototype
 *-----------------------------------------------------------------------------
 */
extern CORBA_Object Create_PseudoNameService_Object(CORBA_long argc,
                                                    CORBA_char **argv,
                                                    CORBA_Environment *ev);
/*
 *-----------------------------------------------------------------------------
 * Forward References
 *-----------------------------------------------------------------------------
 */
void pnamemain_clean_up (CORBA_Environment *ev);
CORBA_boolean RegisterPseudoNameServiceImpl (CORBA_Environment *ev);

/*
 *****************************************************************************
 *
 * Function Name : main
 *
 * Role          : main program entry point for the pseudo name service. This
 *                 creates the pseudo name service object and makes it available.
 *                 This routine should be started first for the entire example.
 *
 *****************************************************************************
 */

int main(int argc, char **argv)
{
    /* local data declaration */
    CORBA_Environment   ev;

    printf("\n***** Pseudo Name Server Started Execution *****\n");

    /* convenience declarations, for similarity to other implementations */
    TheOrb = CORBA_DEC_ORB_OBJECT;
    TheBoa = CORBA_DEC_BOA_OBJECT;

    /* Register the implementation, declare it active */
    if (!RegisterPseudoNameServiceImpl (&ev))  /*side effect: sets global PseudoNameServerImpl*/
        {
	OBB_ORB_rundown (TheOrb, &ev, (CORBA_Flags) 0);
	IsException (&ev,(CORBA_string) "OBB_ORB_rundown failed \n");
	return(0);
        }

    /*Create the object reference, put it in a file */
    pname_ref= Create_PseudoNameService_Object(argc, argv, &ev );

    /* Jump into the main loop. */
    OBB_BOA_main_loop (TheOrb, &ev, (CORBA_Flags)0 );

    /*Finished -- clean up so we don't leave any memory or registration information*/
    pnamemain_clean_up(&ev);

    printf("\n***** PseudoNameService Server Completed Execution *****");

} /* end of main() */
/*
 *****************************************************************************
 *
 *  ROUTINE NAME: RegisterPseudoNameServiceImpl
 *
 *  FUNCTIONAL DESCRIPTION:
 *
 *      Routine to register and activate the PseudoNameService implementation
 *      [Note: similar to that generated by QuickStart]
 *
 *****************************************************************************
 */
CORBA_boolean RegisterPseudoNameServiceImpl (CORBA_Environment *ev)
{
    /* Local Data Declaration */
    CORBA_Flags reg_flags=0;

    /* Register the PseudoNameServiceImpl. PseudoNameServiceImpl__register is created
       in the dispatch file by the "obbgen -d" command.*/
    PseudoNameServiceImpl = PseudoNameServiceImpl__register (
                        PseudoNameServiceImpl__OBJ,
                        ev,
                        (CORBA_NVList) NULL,   /*no additional attrs needed*/
                        (CORBA_NVList) NULL,   /*no server selection needed*/
                        reg_flags);
    if ((PseudoNameServiceImpl == NULL) || (IsException (ev,(CORBA_string)"")))
        {
        printf(CORBA_exception_id(ev));
        printf("\nPseudoNameServiceImpl__register failed \n");
        return(CORBA_FALSE);
        }

    /* Activate the implementation and check for success */
    if (!ActivateImpl(PseudoNameServiceImpl, ev))
        {
        return (CORBA_FALSE);
        }

    return(CORBA_TRUE);
 }
/*
 *****************************************************************************
 *
 * Function Name : pnamemain_clean_up
 *
 * Role          : tidying up to be done.
 *
 *****************************************************************************
 */

void pnamemain_clean_up(CORBA_Environment *ev)
{
    /*The following routines routines are provided through QuickStart, so use
      them instead of trying to exactly match other vendors*/
    DeactivateImpl(PseudoNameServiceImpl, ev);
    UnregisterImpl(PseudoNameServiceImpl, ev);
    CORBA_Object_release((CORBA_Object)PseudoNameServiceImpl, ev);
    OBB_ORB_rundown (TheOrb, ev, (CORBA_Flags) 0);
    printf("\n***Finished tidying up after pseudo name service closed down***");
} /* end of pnamemain_clean_up() */
