/*
 * Method Routines
 * ---------------
 *
 * This module contains method routine templates for the following
 * Implementations:
 *
 *    PseudoNameServiceImpl
 *
 */

#include "pnamesvc.imh"

/* OBB_PRESERVE_BEGIN(INCLUDES) */

/* This module was generated by ObjectBroker, except for the sections between
 * the ...BEGIN and ...END comments (like this comment itself).
 * The sections between such special comment lines were provided by the
 * programmer for this example. In this module, for example, we provide some
 * global definitions, some includes, some global declarations, and three entire
 * routines that are useful to the methods.
 */

#include "db.h"
#include "misc.h"
#include "common.h"
#include <stdlib.h>

/*
 *-----------------------------------------------------------------------------
 * globals -- i.e. externals
 *-----------------------------------------------------------------------------
 */
CORBA_ImplementationDef PseudoNameServiceImpl;

typedef  struct _item
{
  CORBA_Object  obj;
} item_s, *item_p;

typedef struct tagPNameState
{
  DbDb  db;
} PNameState;


/*
 *****************************************************************************
 *
 * Function Name : free_item
 *
 * Role          : free up storage allocated to an item placed in the data store
 *
 *****************************************************************************
 */
void free_item(void *data)
{
  CORBA_Environment  ev;

  CORBA_exception_free(&ev);
  CORBA_Object_release(((item_p)data)->obj, &ev);

} /* end of free_item() */

/*
 *****************************************************************************
 *
 * Function Name : pname_init
 *
 * Role          : perform pseudo name server internal initialisation.
 *
 ***************************************************************************** */
ObjectStatePtr pname_init(void)
{
  PNameState         *ostate;

  /*
   * Create and initialize the first item on the list
   */
  ostate     = malloc(sizeof(PNameState));
  ostate->db = db_init();

  return (ObjectStatePtr)ostate;

} /* end of pname_init() */

/*
 *****************************************************************************
 *
 * Function Name : Create_PseudoNameService_Object
 *
 * Role          : constructor for pseudo name service object
 *
 *****************************************************************************
 */
CORBA_Object Create_PseudoNameService_Object(CORBA_long argc,
                                             CORBA_char **argv,
                                             CORBA_Environment *ev)
{
    CORBA_Object           obj;
    CORBA_ReferenceData    id;
    ObjectStatePtr         objstate;

    objstate = pname_init();      /* application initialisation */

    compose_refdata(&id, objstate);

    obj = CORBA_BOA_create(TheBoa,
                           ev,
                           &id, /*reference data*/
                           PseudoNameService__OBJ,
                           PseudoNameServiceImpl);
    if( ev->_major != CORBA_NO_EXCEPTION )
        application_terminate("Failed to create object",ev );

    /*
     * write object reference to a file
     */

    ref_to_file(obj, ev, PNAME_REF);

    return obj;

} /* end of Create_PseudoNameService_Object() */

/* OBB_PRESERVE_END(INCLUDES) */

/*
 *
 *  ROUTINE NAME: 	PseudoNameServiceImpl__notify
 *
 *  FUNCTIONAL DESCRIPTION:
 *
 *      This is the Event Notification routine for
 *	the PseudoNameServiceImpl implementation.
 */
CORBA_Status OBB_EXPORT PseudoNameServiceImpl__notify (CORBA_Object Object, 
			   CORBA_Environment * Ev,
			   CORBA_Context Context,
			   CORBA_short	Reason,
			   CORBA_short	Subreason,
			   void * Data)

{

    CORBA_Status	status;


    status = OBB_SUCCESS;


   /*
    ** BOA notification to activate or deactivate an implementation or an
    ** object.  The object parameter specifies the implementation or object
    ** that is to be activated or deactivated.
    */
    switch (Reason)
	{

	case OBB_NOTIFY_ACTIVATE_OBJ:
	    break;

	case OBB_NOTIFY_ACTIVATE_IMPL:
	    break;

	case OBB_NOTIFY_DEACTIVATE_OBJ:
	    break;

	case OBB_NOTIFY_DEACTIVATE_IMPL:
	    /*
	    **  We've gotten here because there was a request to
	    **  deactivate this implementation.  Such a request can be
	    **  made via the stop server management command.
	    */

            /* Discontinue dispatching ObjectBroker events. */
            OBB_BOA_exit_main_loop (CORBA_DEC_BOA_OBJECT,
			    Ev,
			    (CORBA_Flags)0 );
	    if (Ev->_major != CORBA_NO_EXCEPTION)
		{
		/*
		**  free any storage that might have been allocated by
		**  ObjectBroker to report the exception
		*/
		CORBA_exception_free(Ev);
		}

	    break;

	default:
	    break;
	}

    return (status);
}

/*
 *
 *  ROUTINE NAME: 	PseudoNameServiceImpl_BindName
 *
 *  FUNCTIONAL DESCRIPTION:
 *
 *      Method routine for BindName.
 *       (Implementation : PseudoNameServiceImpl)
 *
 */

 void PseudoNameServiceImpl_BindName (CORBA_Object object, CORBA_Environment * ev,
    CORBA_string ObjectName,
    CORBA_Object ObjectRef)
{

/* OBB_PRESERVE_BEGIN(PseudoNameServiceImpl_BindName) */
    PNameState  *ostate;
    item_p      anItem;

    ostate = get_state_ptr(TheBoa, ev, object);

    anItem      = malloc (sizeof(item_s));
    anItem->obj = CORBA_Object_duplicate(ObjectRef, ev);

    printf("PseudoNameServiceImpl_Bindname: BindNameing object %s\n", ObjectName);

    db_insert(ObjectName, anItem, free_item, ostate->db);

/* OBB_PRESERVE_END(PseudoNameServiceImpl_BindName) */


    return;
}

/*
 *
 *  ROUTINE NAME: 	PseudoNameServiceImpl_ResolveName
 *
 *  FUNCTIONAL DESCRIPTION:
 *
 *      Method routine for ResolveName.
 *       (Implementation : PseudoNameServiceImpl)
 *
 */

 CORBA_Object PseudoNameServiceImpl_ResolveName (CORBA_Object object, CORBA_Environment * ev,
    CORBA_string ObjectName)
{

/* OBB_PRESERVE_BEGIN(PseudoNameServiceImpl_ResolveName) */
    item_p           theItem;
    PNameState       *ostate;
    CORBA_Object     theObject;

    ostate = get_state_ptr(TheBoa, ev, object);

    if (theItem = db_lookup((char *)ObjectName, ostate->db))
        {
        theObject = theItem->obj;
        printf("PseudoNameServiceImpl_ResolveName: found %s\n", ObjectName);
        }
    else
        {
        /* not found, print debugging output and return NIL */
        printf("PseudoNameServiceImpl_ResolveName: %s not found\n", ObjectName);
        theObject = CORBA_OBJECT_NIL;
        }
    return theObject;

/* OBB_PRESERVE_END(PseudoNameServiceImpl_ResolveName) */


}
