/*
 * POS Client Main
 * ---------------
 *
 * This module contains the main() for a client for the POS, based on POS.idl
 * for Digital Equipment Corporation's (DEC) ObjectBroker C binding
 * and some convenience routines for use by the main. It was originally
 * generated by ObjectBroker's Quick Start utility and then modified to
 * be a little closer to the other vendors.
 *
 */

/* Include Files */
#include <orb.h>
#include <stdio.h>
#include <string.h>
#include <ctype.h>
#include "misc.h"
#include "pos.imh"

/*
 *-----------------------------------------------------------------------------
 * global variables
 *-----------------------------------------------------------------------------
 */

CORBA_ImplementationDef   POSTerminalImpl;      /*filled by RegisterAllImpls, used by others*/
CORBA_ImplementationDef   InputMediaImpl;   /*filled by RegisterAllImpls, used by others*/
static POS_InputMedia     im_ref;
static POS_POSTerminal    post_ref;

/*
 *-----------------------------------------------------------------------------
 * Forward Declarations
 *-----------------------------------------------------------------------------
 */

CORBA_boolean  RegisterAllImpls       (CORBA_Environment *ev);
CORBA_boolean  RegisterPOSTerminalImpl(CORBA_Environment *ev);
CORBA_boolean  RegisterInputMediaImpl (CORBA_Environment *ev);
void           process_input          (void);
void           poscltmain_clean_up    (CORBA_Environment *ev);

/*
 *-----------------------------------------------------------------------------
 * Special external declarations -- function prototypes
 *-----------------------------------------------------------------------------
 */

CORBA_Object Create_POS_POSTerminal_Object(CORBA_long argc,
                                           CORBA_char **argv,
                                           CORBA_Environment *ev);
CORBA_Object Create_POS_InputMedia_Object (CORBA_long argc,
                                           CORBA_char **argv,
                                           CORBA_Environment *ev);

/*
 *
 *  ROUTINE NAME: Main
 *
 *  FUNCTIONAL DESCRIPTION:
 *
 *      This is a platform independent main for the POS client.
 */
CORBA_boolean main (int argc, char *argv[])
{
    /* local data declaration */
    CORBA_Environment   ev;

    printf("\n***** POS Client Started Execution *****\n");

    /* convenience declarations, for similarity to other implementations */
    TheOrb = CORBA_DEC_ORB_OBJECT;
    TheBoa = CORBA_DEC_BOA_OBJECT;


    /* Register the implementation, declare it active */
    if (!RegisterAllImpls (&ev))  /*side effect: sets global xxxImpl*/
        {
        OBB_ORB_rundown (TheOrb, &ev, (CORBA_Flags) 0);
        IsException (&ev,(CORBA_string) "OBB_ORB_rundown failed \n");
        return(0);
        }

    /*Create the object references, register them with the name service*/
    post_ref=Create_POS_POSTerminal_Object(argc, argv, &ev );
    im_ref=  Create_POS_InputMedia_Object(argc, argv, &ev );

    /* Process input from the keyboard. */
    process_input();

    /*Finished -- clean up so we don't leave any memory or registration information*/
    poscltmain_clean_up(&ev);
    return(0);
}

/*
 *****************************************************************************
 *
 * Function Name : process_input
 *
 * Role          : process keyboard input
 *
 *****************************************************************************
 */
void process_input(void)
{
  CORBA_Environment  ev;
  char               instring[STR_MAX+1];

  while (1)
      {
      printf("input: \n");
      fscanf(stdin, "%20s", instring);

      /* if first character is x, leave, if a number, call barcode  else call keypad */

      if (instring[0] == 'x')
          {
          printf("program exit selected");
          return;
          }

      if (isdigit(instring[0]))
          {
          POS_InputMedia_BarcodeInput(im_ref,&ev,instring);
          (void)IsException(&ev,"Failed barcode");
          }
      else
          {
          POS_InputMedia_KeypadInput(im_ref,&ev,instring);
          (void)IsException(&ev,"Failed keycode");
          }
      }

} /* end of process_input() */

/*
 *
 *  ROUTINE NAME: RegisterAllImpls
 *
 *  FUNCTIONAL DESCRIPTION:
 *
 *      Routine to register and activate the POSTerminal and InputMedia implementations
 *
 */
CORBA_boolean RegisterAllImpls (CORBA_Environment *ev)
{
    if (!RegisterPOSTerminalImpl(ev)) return 0;
    if (!RegisterInputMediaImpl(ev))  return 0;
    return 1;
}

/*
 *
 *  ROUTINE NAME: RegisterPOSTerminalImpl
 *
 *  FUNCTIONAL DESCRIPTION:
 *
 *      Routine to register and activate the POSTerminal implementation
 *
 */
CORBA_boolean RegisterPOSTerminalImpl (CORBA_Environment *ev)
{
    /* Local Data Declaration */
    CORBA_Flags reg_flags=0;

    /* Register the POSTerminalImpl. POSTerminalImpl__register is created
       in the dispatch file by the "obbgen -d" command.*/
    POSTerminalImpl = POSTerminalImpl__register (
                        POSTerminalImpl__OBJ,
                        ev,
                        (CORBA_NVList) NULL,   /*no additional attrs needed*/
                        (CORBA_NVList) NULL,   /*no server selection needed*/
                        reg_flags);
    if ((POSTerminalImpl == NULL) || (IsException (ev,(CORBA_string)"")))
        {
        printf("POSTerminalImpl__register failed \n");
        return(CORBA_FALSE);
        }

    /* Activate the implementation and check for success */
    if (!ActivateImpl(POSTerminalImpl, ev))
        {
        return (CORBA_FALSE);
        }

    return(CORBA_TRUE);
 }

/*
 *
 *  ROUTINE NAME: RegisterInputMediaImpl
 *
 *  FUNCTIONAL DESCRIPTION:
 *
 *      Routine to register and activate the InputMedia implementation
 *
 */
CORBA_boolean RegisterInputMediaImpl (CORBA_Environment *ev)
{
    /* Local Data Declaration */
    CORBA_Flags reg_flags=0;

    /* Register the InputMediaImpl. InputMediaImpl__register is created
       in the dispatch file by the "obbgen -d" command.*/
    InputMediaImpl = InputMediaImpl__register (
                        InputMediaImpl__OBJ,
                        ev,
                        (CORBA_NVList) NULL,   /*no additional attrs needed*/
                        (CORBA_NVList) NULL,   /*no server selection needed*/
                        reg_flags);
    if ((InputMediaImpl == NULL) || (IsException (ev,(CORBA_string)"")))
        {
        printf("InputMediaImpl__register failed \n");
        return(CORBA_FALSE);
        }

    /* Activate the implementation and check for success */
    if (!ActivateImpl(InputMediaImpl, ev))
        {
        return (CORBA_FALSE);
        }

    return(CORBA_TRUE);
 }



/*
 *****************************************************************************
 *
 * Function Name : poscltmain_clean_up
 *
 * Role          : tidying up to be done.
 *
 *****************************************************************************
 */

void poscltmain_clean_up(CORBA_Environment *ev)
{
    /*The following routines routines are provided through QuickStart, so use
      them instead of worring about details*/
    DeactivateImpl(POSTerminalImpl, ev);
    UnregisterImpl(POSTerminalImpl, ev);
    CORBA_Object_release((CORBA_Object)POSTerminalImpl, ev);

    DeactivateImpl(InputMediaImpl, ev);
    UnregisterImpl(InputMediaImpl, ev);
    CORBA_Object_release((CORBA_Object)InputMediaImpl, ev);

    OBB_ORB_rundown (TheOrb, ev, (CORBA_Flags) 0);

} /* end of depotmain_clean_up() */
