/*
 * Store Server Main
 * -----------------
 *
 * This module contains the main() for a server based on store.idl
 * for Digital Equipment Corporation's (DEC) ObjectBroker C binding
 * and some convenience routines for use by the main. It was originally
 * generated by ObjectBroker's Quick Start utility and then modified to
 * be a little closer to the other vendors.
 *
 */

/* Include Files */
#include <orb.h>
#include <stdio.h>
#include <string.h>
#include "misc.h"
#include "astore.imh"

/*
 *-----------------------------------------------------------------------------
 * global variables
 *-----------------------------------------------------------------------------
 */

CORBA_ImplementationDef   StoreImpl;      /*filled by RegisterAllImpls, used by others*/
CORBA_ImplementationDef   StoreAccessImpl;   /*filled by RegisterAllImpls, used by others*/
CORBA_ImplementationDef   TaxImpl;        /*filled by RegisterAllImpls, used by others*/

/*
 *-----------------------------------------------------------------------------
 * Forward Declarations
 *-----------------------------------------------------------------------------
 */

CORBA_boolean  RegisterAllImpls       (CORBA_Environment *ev);
CORBA_boolean  RegisterStoreImpl      (CORBA_Environment *ev);
CORBA_boolean  RegisterStoreAccessImpl(CORBA_Environment *ev);
CORBA_boolean  RegisterTaxImpl        (CORBA_Environment *ev);
void           storemain_clean_up     (CORBA_Environment *ev);

/*
 *-----------------------------------------------------------------------------
 * Special external declarations -- function prototypes
 *-----------------------------------------------------------------------------
 */

CORBA_Object Create_AStore_Store_Object(CORBA_long argc,
                                        CORBA_char **argv,
                                        CORBA_Environment *ev);
CORBA_Object Create_AStore_Tax_Object  (CORBA_long argc,
                                        CORBA_char **argv,
                                        CORBA_Environment *ev);

/*
 *
 *  ROUTINE NAME: Main
 *
 *  FUNCTIONAL DESCRIPTION:
 *
 *      This is a platform independent main for the Store Server.
 */
CORBA_boolean main (int argc, char *argv[])
{
    /* local data declaration */
    CORBA_Environment   ev;

    printf("\n***** Store Server Started Execution *****\n");

    /* convenience declarations, for similarity to other implementations */
    TheOrb = CORBA_DEC_ORB_OBJECT;
    TheBoa = CORBA_DEC_BOA_OBJECT;


    /* Register the implementation, declare it active */
    if (!RegisterAllImpls (&ev))  /*side effect: sets global xxxImpl*/
        {
        OBB_ORB_rundown (TheOrb, &ev, (CORBA_Flags) 0);
        IsException (&ev,(CORBA_string) "OBB_ORB_rundown failed \n");
        return(0);
        }

    /*Create the object reference, register it with the name service*/
    (void)Create_AStore_Tax_Object(argc, argv, &ev );
    (void)Create_AStore_Store_Object(argc, argv, &ev );

    /* Jump into the main loop. */
    OBB_BOA_main_loop (TheOrb, &ev, (CORBA_Flags)0 );

    /*Finished -- clean up so we don't leave any memory or registration information*/
    storemain_clean_up(&ev);
    return(0);
}


/*
 *
 *  ROUTINE NAME: RegisterAllImpls
 *
 *  FUNCTIONAL DESCRIPTION:
 *
 *      Routine to register and activate the Store implementation
 *
 */
CORBA_boolean RegisterAllImpls (CORBA_Environment *ev)
{
    if (!RegisterStoreImpl(ev))       return 0;
    if (!RegisterStoreAccessImpl(ev)) return 0;
    if (!RegisterTaxImpl(ev))         return 0;
    return 1;
}
/*
 *
 *  ROUTINE NAME: RegisterStoreImpl
 *
 *  FUNCTIONAL DESCRIPTION:
 *
 *      Routine to register and activate the Store implementation
 *
 */
CORBA_boolean RegisterStoreImpl (CORBA_Environment *ev)
{
    /* Local Data Declaration */
    CORBA_Flags reg_flags=0;

    /* Register the StoreImpl. StoreImpl__register is created
       in the dispatch file by the "obbgen -d" command.*/
    StoreImpl = StoreImpl__register (
                        StoreImpl__OBJ,
                        ev,
                        (CORBA_NVList) NULL,   /*no additional attrs needed*/
                        (CORBA_NVList) NULL,   /*no server selection needed*/
                        reg_flags);
    if ((StoreImpl == NULL) || (IsException (ev,(CORBA_string)"")))
        {
        printf("StoreImpl__register failed \n");
        return(CORBA_FALSE);
        }

    /* Activate the implementation and check for success */
    if (!ActivateImpl(StoreImpl, ev))
        {
        return (CORBA_FALSE);
        }

    return(CORBA_TRUE);
 }
/*
 *
 *  ROUTINE NAME: RegisterStoreAccessImpl
 *
 *  FUNCTIONAL DESCRIPTION:
 *
 *      Routine to register and activate the StoreAccess implementation
 *
 */
CORBA_boolean RegisterStoreAccessImpl (CORBA_Environment *ev)
{
    /* Local Data Declaration */
    CORBA_Flags reg_flags=0;

    /* Register the StoreAccessImpl. StoreAccessImpl__register is created
       in the dispatch file by the "obbgen -d" command.*/
    StoreAccessImpl = StoreAccessImpl__register (
                        StoreAccessImpl__OBJ,
                        ev,
                        (CORBA_NVList) NULL,   /*no additional attrs needed*/
                        (CORBA_NVList) NULL,   /*no server selection needed*/
                        reg_flags);
    if ((StoreAccessImpl == NULL) || (IsException (ev,(CORBA_string)"")))
        {
        printf("StoreAccessImpl__register failed \n");
        return(CORBA_FALSE);
        }

    /* Activate the implementation and check for success */
    if (!ActivateImpl(StoreAccessImpl, ev))
        {
        return (CORBA_FALSE);
        }

    return(CORBA_TRUE);
 }
/*
 *
 *  ROUTINE NAME: RegisterTaxImpl
 *
 *  FUNCTIONAL DESCRIPTION:
 *
 *      Routine to register and activate the Tax implementation
 *
 */
CORBA_boolean RegisterTaxImpl (CORBA_Environment *ev)
{
    /* Local Data Declaration */
    CORBA_Flags reg_flags=0;

    /* Register the TaxImpl. TaxImpl__register is created
       in the dispatch file by the "obbgen -d" command.*/
    TaxImpl = TaxImpl__register (
                        TaxImpl__OBJ,
                        ev,
                        (CORBA_NVList) NULL,   /*no additional attrs needed*/
                        (CORBA_NVList) NULL,   /*no server selection needed*/
                        reg_flags);
    if ((TaxImpl == NULL) || (IsException (ev,(CORBA_string)"")))
        {
        printf("TaxImpl__register failed \n");
        return(CORBA_FALSE);
        }

    /* Activate the implementation and check for success */
    if (!ActivateImpl(TaxImpl, ev))
        {
        return (CORBA_FALSE);
        }

    return(CORBA_TRUE);
 }


/*
 *****************************************************************************
 *
 * Function Name : storemain_clean_up
 *
 * Role          : tidying up to be done.
 *
 *****************************************************************************
 */

void storemain_clean_up(CORBA_Environment *ev)
{
    /*The following routines routines are provided through QuickStart, so use
      them instead of worring about details*/
    DeactivateImpl(StoreImpl, ev);
    UnregisterImpl(StoreImpl, ev);
    CORBA_Object_release((CORBA_Object)StoreImpl, ev);

    DeactivateImpl(StoreAccessImpl, ev);
    UnregisterImpl(StoreAccessImpl, ev);
    CORBA_Object_release((CORBA_Object)StoreAccessImpl, ev);

    DeactivateImpl(TaxImpl, ev);
    UnregisterImpl(TaxImpl, ev);
    CORBA_Object_release((CORBA_Object)TaxImpl, ev);

    OBB_ORB_rundown (TheOrb, ev, (CORBA_Flags) 0);
    printf("\n***Tidying up after store services closed down***");

} /* end of depotmain_clean_up() */
