#if !defined(AFX_XFLOORWND_H__D46E5D11_87ED_11D2_871A_0040055C08D9__INCLUDED_)
#define AFX_XFLOORWND_H__D46E5D11_87ED_11D2_871A_0040055C08D9__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class COleFont;

/////////////////////////////////////////////////////////////////////////////
// CXFloorWnd wrapper class

class CXFloorWnd : public CWnd
{
protected:
	DECLARE_DYNCREATE(CXFloorWnd)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0x24ffd1ed, 0x5ea9, 0x11d2, { 0x86, 0xb1, 0x0, 0x40, 0x5, 0x5c, 0x8, 0xd9 } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:
	OLE_COLOR GetBackColor();
	void SetBackColor(OLE_COLOR);
	BOOL GetAnimation();
	void SetAnimation(BOOL);
	long GetSleep();
	void SetSleep(long);
	BOOL GetSign();
	void SetSign(BOOL);
	CString GetPages();
	void SetPages(LPCTSTR);
	COleFont GetFont();
	void SetFont(LPDISPATCH);
	BOOL GetAsPage();
	void SetAsPage(BOOL);

// Operations
public:
	short AddPage(LPCTSTR sName);
	BOOL DeletePage(short nIndex);
	CString GetPageName(short nIndex);
	short GetPage(LPCTSTR lpszPageName);
	BOOL ActivatePage(short nIndex);
	BOOL AttachWindow(short nIndex, long pWnd);
	BOOL SetPageName(short nIndex, LPCTSTR lpszPageName);
	void Init();
	short GetHeight(short nIndex);
	void SetHeight(short nIndex, short nNewValue);
	unsigned long GetColor(short nIndex);
	void SetColor(short nIndex, unsigned long newValue);
	long GetUserData(short nIndex);
	void SetUserData(short nIndex, long nNewValue);
	short GetActivePage();
	long GetPagesCount();
	BOOL IsPage(short nIndex);
	long GetLeftTopPage(short nIndex);
	long GetBottomRightPage(short nIndex);
	void StyleAs(BOOL bAsFloor);
	long GetHWnd(long nIndex);
	void AboutBox();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_XFLOORWND_H__D46E5D11_87ED_11D2_871A_0040055C08D9__INCLUDED_)
